### ISSUE TITLE
Full HTTP Proxy protocol support for a "Home VPN" 

### ISSUE THREAD

**Issue by TheRook** [ao-space/gt#29]
I need a full HTTP Proxy over a websocket and i noticed GT is pretty similar. 

The use-case here for a full proxy is you are traveling and you want to be able to watch TV from home.   Sure I can use WireGuard or something like [WebMesh](https://github.com/webmeshproj/webmesh) which is a zero-config way of setting up a VPN. But...  what if i want to access this VPN with a websocket?  

GT will only forward to a specific host, but the HTTP Proxy protocol lets the client specify *any* host so that they can browse the web without censorship or being tracked.   And this could work with the current GT web tunnel.

There is also the [wssocks project which is Socks5 over websockets](https://github.com/genshen/wssocks) - in golang, which might be useful here?

Thoughts?

**Comment by vyloy** [comment]
GT can do that by running a socks proxy server with GT client and using TCP relay configuration.

Example of GT client configuration file:
```yaml
version: 1.0
services:
  # run a socks proxy server on local with port 1080 or any port you want and then update the value of local
  - local: tcp://127.0.0.1:1080
    # port to open on GT server
    remoteTCPPort: 11080
    # open a random port on GT server if port was used
    remoteTCPRandom: true
options:
  id: id-should-be-overwritten
  secret: secret-should-be-overwritten
  # GT server address
  # remote: tls://1.1.1.1:4443
  remote: tcp://1.1.1.1:80
  remoteConnections: 5
  logLevel: info
```

Now enjoy the socks proxy by using port 11080 on GT server. 

Does this solution sound ok to you?
